### ISSUE TITLE
null is not an object ( evaluating ;this.state.visible';)

### ISSUE THREAD

**Issue by kri-yor** [raynor85/react-native-modal-wrapper#5]
Hello,
excuse me for the probably stupid question. I am really new to React, I wa trying to get the Modal without overlay example up and running but i get this error : null is not an object ( evaluating ;this.state.visible';) when I try to run the program. I am probably missing something, maybe call it from somewhere when I click a button, but I am not sure how. 

Thank you !

**Comment by raynor85** [comment]
It looks like you simply copied and pasted the example from the README.md. These examples are not complete and their purpose is just to highlight the API of the modal wrapper. In that example this.state represents the state of the component that uses the modal wrapper, and this.state.visible logically represents the visibility of the modal wrapper, since it is passed as prop to determine its visibility. If you are not familiar with the basis of react I suggest you to study it a little bit, and you can start from taking a look at props and state.
props:
https://facebook.github.io/react/docs/components-and-props.html
state:
https://facebook.github.io/react/docs/state-and-lifecycle.html
I'm closing this because it is not an issue.
