### ISSUE TITLE
Possible to have scrollable content inside?

### ISSUE THREAD

**Issue by mik-rom** [raynor85/react-native-modal-wrapper#6]
First of all, thanks for creating this module. I've tried a few dialog components and this is the first one where keyboard avoiding seems to work out of the box.

I have one problem though. I have tried adding a ScrollView inside my modal but it doesn't scroll. I set the modal style height to 200 and the ScrollView contentContainerStyle to 300 so that the content is clipped. In my mind this should make the dialog scrollable but it doesn't. Any ideas on how to make this work?

**Comment by raynor85** [comment]
I am using scrollviews inside my modal and they work just fine. Do you have a code example so I can help you better?

**Comment by raynor85** [comment]
I'm pretty sure the problem is in the scrollview, because the modal is just any normal container. Try to add background colours to both the scrollview (style) and the related content view (contentContainerStyle) to see where the elements are, and if you use a simple text in the scrollview be sure its colour doesn't match the background colours. Sorry for the silly advice but I cannot think of anything else without a coding example.

**Comment by mik-rom** [comment]
Thanks for the reply. You might be right that it's the scroll view, i
haven't dug too deep into it, I will do some more testing soon. I
experienced the problem on android, haven't tried on iOS yet.
