### ISSUE TITLE
Possible to bring modal into the interaction space after initiating via onLongPress? 

### ISSUE THREAD

**Issue by GollyJer** [raynor85/react-native-modal-wrapper#8]
Hi @raynor85.  Thanks a ton for this project.  It's made modals super easy to implement.

The last thing I'm trying to do is initiate a modal via onLongPress and, with the finger still on the screen, interact with the modal.

Do you use instagram?  If so, go to your profile section to view all the photos you've posted. Tap and hold one a photo thumbnail.  The photo will pop up in a modal and you can then drag your finger to a few buttons on the bottom to take actions on the photo.

This is what I'm trying to implement, without success so far.

I'm not sure it's possible but I thought I'd ask.

Thanks!!
Jeremy

**Comment by raynor85** [comment]
I personally never coded a draggable component using react native, but
there are many examples and modules available on the Internet. I don't
understand why you should need a draggable moral box in the first place, it
seems you just need the draggable component.
Ps: about instagram, are you referring at the 3D Touch on ios?

**Comment by GollyJer** [comment]
Hey! Thanks for the response.

It's not a draggable component. I guess it's hard to explain if you haven't seen it. I'm using Instagram on android and it works via tap and-hold.

I'll take a video when I get a chance.

**Comment by GollyJer** [comment]
Hi @raynor85. I was able to get a quick video of the Instagram interaction.
[Take a look](https://goo.gl/photos/B7Ecgs1EbnqsuJmj8)!

**Comment by raynor85** [comment]
As an iPhone owner, that popup is activated using the 3D touch capability of iOS modern devices. This gesture is replicated for Android users with a longer press which is totally unrelated of the intensity of the pressure (more info: https://www.theverge.com/2015/12/8/9871248/apple-3d-touch-on-android-instagram-limited-update)
Now that we are in the same page, according to the article I posted above this is a very specific gesture for a very specific use case. Feel free to fork my project and try to play with the code, it's very simple and well documented, as the current API are limited to click gestures of opening and closing. You probably need to add a PanResponder or even go more in depth in order to detect the touchup event to close the modal
https://facebook.github.io/react-native/docs/gesture-responder-system.html
