### ISSUE TITLE
Modal not rotating with device orientation for iOS, working for Android

### ISSUE THREAD

**Issue by kckunal2612** [raynor85/react-native-modal-wrapper#9]
React Native's default Modal component enables us to add a prop " supportedOrientations" that allows the modal to be rotated to any of the specified orientations (for iOS, since it rotates on its own on Android). 
However, there is not any provision for us to set that property in this library, which is rotating the modal dialog to portrait orientation even if the device is in landscape mode. Could you kindly help solve this issue ? Thanks !

**Comment by raynor85** [comment]
As the documentation of react-native-modal-wrapper says, ModalWrapper accepts all the props the original Modal accepts, therefore you can just pass it in the same way you would pass it to the native component.
https://facebook.github.io/react-native/docs/modal.html
For example, if you want your modal to support both portrait and landscape mode, you have to pass:

`supportedOrientations={['portrait', 'landscape']}`

I suggest to check out Supported interface orientations key in the plist of your iOS project. In my project I was able to make the modal rotate after adding these properties:

```
<key>UISupportedInterfaceOrientations</key>
<array>
	<string>UIInterfaceOrientationPortrait</string>
	<string>UIInterfaceOrientationLandscapeLeft</string>
	<string>UIInterfaceOrientationLandscapeRight</string>
	<string>UIInterfaceOrientationPortraitUpsideDown</string>
</array>
```

**Comment by kckunal2612** [comment]
It worked perfectly ! Thanks a ton !

**Comment by raynor85** [comment]
I'm glad, and thank you for using the plugin.

**Comment by kckunal2612** [comment]
Thanks for the library !

**Comment by kckunal2612** [comment]
How can I disable rotation for the Modal ?
I have set "supportedOrientations" to "portrait" only in the code, and it works fine for iOS.
However, I want to disable the orienatation change for Android as well, but the ModalWrapper doesn't seem to respond to system orientation changes.

**Comment by raynor85** [comment]
This is not an issue of ModalWrapper per se. According to the documentation https://facebook.github.io/react-native/docs/modal.html, supportedOrientations is an iOS specific prop. On android the modal behaves differently. You have to ask yourself which problem you are trying to solve. If the problem is locking the orientation for the whole app, that article could be enough:
https://medium.com/react-native-training/react-native-portrait-device-orientation-9bcdeeac0b03.
If you want to have more flexibility and lock the orientation on given conditions (for example lock it when the modal opens and restore it when the modal closes), check out this plugin: https://github.com/yamill/react-native-orientation.
